name: go_local_vendor
description: A new Flutter application.
publish_to: 'none'
version: 1.2.0+3
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_icons: ^1.1.0
  cached_network_image: ^2.3.3
  carousel_slider: ^3.0.0
  flutter_rating_bar: ^4.0.0
  image_picker: ^0.6.7+4
  flutter_bloc: ^6.1.2
  http: ^0.12.2
  device_info: ^2.0.0
  shared_preferences: ^0.5.10
  chips_choice: ^1.4.1
  webview_flutter: ^2.0.2
  cupertino_icons: ^1.0.2
  xml: ^4.5.1
  permission_handler: ^5.0.1+1
  flutter_launcher_icons: ^0.8.1
  url_launcher: ^6.0.2
  double_back_to_close_app: ^2.0.1
  meta: ^1.2.4
  google_fonts: ^1.1.2
  flutter_launcher_name: ^0.0.1
  date_format: ^2.0.2
  #fluttertoast: ^7.1.8
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_name:
  name: "GoLocal UAE"
flutter_icons:
  android: "launcher"
  ios: true
  image_path: "assets/images/GoLocal_LOGO.png"
#  flutter pub run flutter_launcher_icons:main

flutter:
  uses-material-design: true
  assets:
    - assets/images/